// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dd5e3a61-678f-4b6d-a1f9-740a88ab7b8a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ji1XSAE1l",
    "aws_user_pools_web_client_id": "7k39vnd7q5bv3bb41b4ricr2u7",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "hotels",
            "endpoint": "https://a5eqznt3z3.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
